# Generated by Django 5.1.1 on 2024-09-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0002_categoria_producto_categoria_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='url_imagen',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
